### ISSUE TITLE
error

### ISSUE THREAD

**Issue by UsboKirishima** [AdamEssemaali/AnimeCLI#2]
input: `python3 main.py`

output: `
Traceback (most recent call last):
  File "/run/media/usbo/Volume/AnimeCLI/main.py", line 49, in <module>
    animes = findAnime(sys.argv[1])
IndexError: list index out of range
`

![image](https://media.discordapp.net/attachments/993385089041969225/1004715176102219796/unknown.png?width=447&height=112)

**Comment by AdamEssemaali** [comment]
You have to specify the Args (i'll implement some error management)
Thx for the issue :)
